### ISSUE TITLE
Make a new release!

### ISSUE THREAD

**Issue by asottile** [Yelp/gprof2dot#13]
CC @ArnaudBrousseau

Looking for the commits from #11 to be in a release <3

**Comment by ArnaudBrousseau** [comment]
Oh hai! 👋 

[v1.2.0](https://github.com/Yelp/gprof2dot/tree/v1.2.0) contains changes from #11. You're talking about a [pypi release](https://pypi.org/project/yelp-gprof2dot/#history) I imagine? Let me see if I have the credentials to make this happen (it's been a while!)

**Comment by asottile** [comment]
`setup.py` still lists 1.1.0 also so make sure to update that :D https://github.com/Yelp/gprof2dot/blob/f1cf6bbf0fccb1610b76e42a32edf7aa2da74cd2/setup.py#L21

**Comment by ArnaudBrousseau** [comment]
Should be good! I don't have the privileges to mark this as closed or assign myself, but:

* new version (1.2.0) is available at https://pypi.org/project/yelp-gprof2dot/1.2.0/
* PR with the minor edits I made before uploading is at #14

**Comment by asottile** [comment]
Thanks!
